using System.Text.Json;
using ThesisDocx.Core.Models.Requirements;
using ThesisDocx.Core.Models.Templates;
using ThesisDocx.Core.Requirements;
using ThesisDocx.Core.Utilities;
using ThesisDocx.Core.Validation;

namespace ThesisDocx.Core.Onboarding;

public sealed class OnboardingWorkspaceInitializer
{
    public OnboardingWorkspaceManifest Initialize(OnboardingWorkspaceInitOptions options)
    {
        var workspaceRoot = Path.GetFullPath(options.WorkspacePath);
        Directory.CreateDirectory(workspaceRoot);
        var manifestPath = Path.Combine(workspaceRoot, "onboarding.json");
        if (File.Exists(manifestPath) && !options.Force)
        {
            throw new InvalidOperationException("Onboarding workspace already exists. Pass --force to overwrite onboarding.json.");
        }

        var manifest = new OnboardingWorkspaceManifest
        {
            WorkspaceId = Slug(options.College.Length > 0 ? options.College : options.School),
            DisplayName = $"{options.School} {options.College}".Trim(),
            Institution = new OnboardingInstitution
            {
                School = options.School,
                College = options.College,
                DegreeType = options.DegreeType,
                Locale = options.Locale,
                IsRealInstitution = options.IsRealInstitution,
                RedactionPolicy = options.IsRealInstitution ? "privateWorkspaceOnly" : "fictionalExample"
            },
            WorkspaceRoot = workspaceRoot
        };

        CreateWorkspaceDirectories(workspaceRoot, manifest.Paths);
        File.WriteAllText(manifestPath, JsonSerializer.Serialize(manifest, ThesisJson.Options));
        WriteWorkspaceGitIgnore(workspaceRoot);
        return manifest;
    }

    public void ScaffoldRequirements(string workspacePath, bool force)
    {
        var workspace = OnboardingWorkspaceInspector.Load(workspacePath);
        var path = workspace.RequirementsFile;
        EnsureCanWrite(path, force);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var capture = new RequirementCapture
        {
            Id = $"{workspace.Manifest.WorkspaceId}-requirements",
            Title = $"{workspace.Manifest.DisplayName} requirement capture draft",
            School = workspace.Manifest.Institution.School,
            College = workspace.Manifest.Institution.College,
            DegreeType = workspace.Manifest.Institution.DegreeType,
            Locale = workspace.Manifest.Institution.Locale,
            SourceDocuments =
            [
                new RequirementSource
                {
                    Id = "manual-1",
                    Title = "Manual source placeholder",
                    Type = RequirementSourceType.ManualNote,
                    Path = "source-documents/README.md",
                    CapturedAt = "2026-05-05T00:00:00Z",
                    Notes = "Manual entry placeholder. Do not paste long copyrighted excerpts."
                }
            ],
            Requirements =
            [
                new RequirementItem
                {
                    Id = "req-page-setup",
                    Category = RequirementCategory.PageSetup,
                    Title = "Page setup requirement",
                    Description = "Fill this item manually from the approved college requirement.",
                    SourceId = "manual-1",
                    Evidence = new RequirementEvidence { ShortQuote = "Short excerpt only.", Section = "Page setup" },
                    NormalizedValue = "TBD",
                    TargetSpecPath = "$.pageSetup",
                    Confidence = RequirementConfidence.Medium,
                    ReviewStatus = RequirementReviewStatus.Draft,
                    Notes = "Draft placeholder generated by onboarding scaffold."
                }
            ],
            Mappings =
            [
                new RequirementMapping
                {
                    RequirementId = "req-page-setup",
                    SpecPath = "$.pageSetup",
                    MappingStatus = RequirementMappingStatus.Partial,
                    Notes = "Update after manual review."
                }
            ],
            Approval = new RequirementApproval
            {
                PreparedBy = "Template Author",
                Notes = "Draft generated by onboarding scaffold; not AI parsed."
            }
        };
        File.WriteAllText(path, JsonSerializer.Serialize(capture, ThesisJson.Options));
        workspace.Manifest.Status.Phase = OnboardingPhase.RequirementsDrafted;
        Save(workspace);
    }

    public void ScaffoldTemplate(string workspacePath, string baseTemplatePath, bool force)
    {
        var workspace = OnboardingWorkspaceInspector.Load(workspacePath);
        CopyDirectory(baseTemplatePath, workspace.TemplateDirectory, force);
        workspace.Manifest.Status.Phase = OnboardingPhase.TemplateScaffolded;
        Save(workspace);
    }

    public void ScaffoldFixtures(string workspacePath, string documentPath, bool force)
    {
        var workspace = OnboardingWorkspaceInspector.Load(workspacePath);
        Directory.CreateDirectory(workspace.FixturesDirectory);
        var target = Path.Combine(workspace.FixturesDirectory, "document.json");
        EnsureCanWrite(target, force);
        File.Copy(documentPath, target, overwrite: force);
        var readme = Path.Combine(workspace.FixturesDirectory, "README.md");
        if (force || !File.Exists(readme))
        {
            File.WriteAllText(readme, "# Onboarding fixtures\n\nFictional or redacted fixtures for template pilot validation.\n");
        }

        workspace.Manifest.Status.Phase = OnboardingPhase.FixturesScaffolded;
        Save(workspace);
    }

    public void InitializeBaselines(string workspacePath, string reason, bool force = false)
    {
        if (string.IsNullOrWhiteSpace(reason))
        {
            throw new InvalidOperationException("Baseline initialization requires a reason.");
        }

        var workspace = OnboardingWorkspaceInspector.Load(workspacePath);
        Directory.CreateDirectory(workspace.BaselinesDirectory);
        var target = Path.Combine(workspace.BaselinesDirectory, "baseline-manifest.json");
        EnsureCanWrite(target, force);
        var manifest = new
        {
            schemaVersion = "1.0.0",
            suiteId = $"{workspace.Manifest.WorkspaceId}-onboarding",
            generatedAt = "2026-05-05T00:00:00Z",
            baselines = new[]
            {
                new
                {
                    caseId = $"{workspace.Manifest.WorkspaceId}-full",
                    templateId = workspace.Manifest.WorkspaceId,
                    templateVersion = "1.0.0",
                    documentId = "fixtures/document.json",
                    snapshotPath = "full.snapshot.txt",
                    layoutSignaturePath = "full.layout.json",
                    inspectPath = "full.inspect.json",
                    structureDiffPolicy = "breakingChangesFail",
                    layoutThreshold = workspace.Manifest.Quality.LayoutThreshold,
                    allowedDiffCategories = Array.Empty<string>(),
                    forbiddenDiffCategories = new[] { "pageSetup", "heading", "table", "figure", "equation" },
                    lastUpdatedAt = "2026-05-05T00:00:00Z",
                    notes = reason
                }
            }
        };
        File.WriteAllText(target, JsonSerializer.Serialize(manifest, ThesisJson.Options));
        workspace.Manifest.Status.Phase = OnboardingPhase.BaselinesInitialized;
        Save(workspace);
    }

    internal static void CreateWorkspaceDirectories(string root, OnboardingWorkspacePaths paths)
    {
        foreach (var path in new[]
        {
            paths.SourceDocumentsDir,
            Path.GetDirectoryName(paths.RequirementsPath) ?? string.Empty,
            paths.TemplateDir,
            paths.FixturesDir,
            paths.BaselinesDir,
            paths.ReportsDir,
            paths.ArtifactsDir
        }.Where(value => !string.IsNullOrWhiteSpace(value)))
        {
            Directory.CreateDirectory(Path.Combine(root, path));
        }
    }

    private static void WriteWorkspaceGitIgnore(string workspaceRoot)
    {
        var path = Path.Combine(workspaceRoot, ".gitignore");
        if (File.Exists(path))
        {
            return;
        }

        File.WriteAllText(path, """
        source-documents/
        artifacts/
        reports/*.zip
        *.pdf
        *.docx
        *.doc
        *.wps
        *.ttf
        *.otf
        *.ttc
        """);
    }

    private static void CopyDirectory(string source, string target, bool force)
    {
        if (!Directory.Exists(source))
        {
            throw new DirectoryNotFoundException(source);
        }

        foreach (var directory in Directory.EnumerateDirectories(source, "*", SearchOption.AllDirectories))
        {
            Directory.CreateDirectory(directory.Replace(source, target, StringComparison.Ordinal));
        }

        Directory.CreateDirectory(target);
        foreach (var file in Directory.EnumerateFiles(source, "*", SearchOption.AllDirectories))
        {
            var destination = file.Replace(source, target, StringComparison.Ordinal);
            EnsureCanWrite(destination, force);
            Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
            File.Copy(file, destination, overwrite: force);
        }
    }

    private static void EnsureCanWrite(string path, bool force)
    {
        if (File.Exists(path) && !force)
        {
            throw new InvalidOperationException($"File already exists: {path}. Pass --force to overwrite.");
        }
    }

    private static string Slug(string value)
    {
        var chars = value.ToLowerInvariant()
            .Select(ch => char.IsLetterOrDigit(ch) ? ch : '-')
            .ToArray();
        return string.Join('-', new string(chars).Split('-', StringSplitOptions.RemoveEmptyEntries));
    }

    private static void Save(ResolvedOnboardingWorkspace workspace)
    {
        File.WriteAllText(Path.Combine(workspace.Root, "onboarding.json"), JsonSerializer.Serialize(workspace.Manifest, ThesisJson.Options));
    }
}

public sealed class OnboardingWorkspaceInitOptions
{
    public string WorkspacePath { get; set; } = string.Empty;

    public string School { get; set; } = string.Empty;

    public string College { get; set; } = string.Empty;

    public string DegreeType { get; set; } = "master";

    public string Locale { get; set; } = "zh-CN";

    public bool IsRealInstitution { get; set; }

    public bool Force { get; set; }
}

public sealed class OnboardingWorkspaceInspector
{
    public static ResolvedOnboardingWorkspace Load(string workspacePath)
    {
        var root = Path.GetFullPath(workspacePath);
        var manifestPath = Path.Combine(root, "onboarding.json");
        var manifest = JsonSerializer.Deserialize<OnboardingWorkspaceManifest>(File.ReadAllText(manifestPath), ThesisJson.Options)
            ?? throw new InvalidOperationException($"Could not deserialize {manifestPath}.");
        manifest.WorkspaceRoot = root;
        return new ResolvedOnboardingWorkspace(root, manifest);
    }

    public OnboardingWorkspaceInspection Inspect(string workspacePath)
    {
        var workspace = Load(workspacePath);
        var validator = new OnboardingWorkspaceValidator().Validate(workspacePath);
        return new OnboardingWorkspaceInspection
        {
            WorkspaceId = workspace.Manifest.WorkspaceId,
            DisplayName = workspace.Manifest.DisplayName,
            Phase = workspace.Manifest.Status.Phase.ToString(),
            Root = workspace.Root,
            IsValid = validator.IsValid,
            Errors = validator.Errors,
            Warnings = validator.Warnings,
            Paths = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["requirements"] = workspace.RequirementsFile,
                ["template"] = workspace.TemplateDirectory,
                ["fixtures"] = workspace.FixturesDirectory,
                ["baselines"] = workspace.BaselinesDirectory,
                ["reports"] = workspace.ReportsDirectory,
                ["artifacts"] = workspace.ArtifactsDirectory
            }
        };
    }
}

public sealed record ResolvedOnboardingWorkspace(string Root, OnboardingWorkspaceManifest Manifest)
{
    public string RequirementsFile => Path.Combine(Root, Manifest.Paths.RequirementsPath);
    public string TemplateDirectory => Path.Combine(Root, Manifest.Paths.TemplateDir);
    public string FixturesDirectory => Path.Combine(Root, Manifest.Paths.FixturesDir);
    public string BaselinesDirectory => Path.Combine(Root, Manifest.Paths.BaselinesDir);
    public string ReportsDirectory => Path.Combine(Root, Manifest.Paths.ReportsDir);
    public string ArtifactsDirectory => Path.Combine(Root, Manifest.Paths.ArtifactsDir);
    public string SourceDocumentsDirectory => Path.Combine(Root, Manifest.Paths.SourceDocumentsDir);
    public string DocumentPath => Path.Combine(FixturesDirectory, "document.json");
}

public sealed class OnboardingWorkspaceInspection
{
    public string WorkspaceId { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string Phase { get; set; } = string.Empty;
    public string Root { get; set; } = string.Empty;
    public bool IsValid { get; set; }
    public List<OnboardingWorkspaceIssue> Errors { get; set; } = [];
    public List<OnboardingWorkspaceIssue> Warnings { get; set; } = [];
    public Dictionary<string, string> Paths { get; set; } = new(StringComparer.Ordinal);
}

public sealed class OnboardingWorkspaceValidator
{
    public OnboardingWorkspaceValidationResult Validate(string workspacePath)
    {
        var result = new OnboardingWorkspaceValidationResult();
        var root = Path.GetFullPath(workspacePath);
        var manifestPath = Path.Combine(root, "onboarding.json");
        if (!File.Exists(manifestPath))
        {
            Add(result, true, "onboarding.manifest.missing", "$", "Missing onboarding.json.");
            return result;
        }

        var schemaPath = LocateSchema("onboarding-workspace.schema.json");
        if (File.Exists(schemaPath))
        {
            var schema = new ThesisSchemaValidator().ValidateOnboardingWorkspaceFile(manifestPath, schemaPath);
            foreach (var error in schema.Errors)
            {
                Add(result, true, error.Code, error.Path, error.Message);
            }
        }

        var workspace = OnboardingWorkspaceInspector.Load(root);
        if (!OnboardingWorkspaceSchemaVersions.IsSupported(workspace.Manifest.SchemaVersion))
        {
            Add(result, true, "onboarding.schemaVersion.unsupported", "$.schemaVersion", "Unsupported onboarding schemaVersion.");
        }

        foreach (var (name, value) in EnumeratePaths(workspace.Manifest.Paths))
        {
            if (IsInvalidRelativePath(value))
            {
                Add(result, true, "onboarding.path.invalid", $"$.paths.{name}", $"Path must be relative and inside workspace: {value}");
                continue;
            }
        }

        foreach (var (path, code) in new[]
        {
            (workspace.SourceDocumentsDirectory, "onboarding.path.sourceDocumentsMissing"),
            (Path.GetDirectoryName(workspace.RequirementsFile)!, "onboarding.path.requirementsDirMissing"),
            (workspace.TemplateDirectory, "onboarding.path.templateDirMissing"),
            (workspace.FixturesDirectory, "onboarding.path.fixturesDirMissing"),
            (workspace.BaselinesDirectory, "onboarding.path.baselinesDirMissing"),
            (workspace.ReportsDirectory, "onboarding.path.reportsDirMissing"),
            (workspace.ArtifactsDirectory, "onboarding.path.artifactsDirMissing")
        })
        {
            if (!Directory.Exists(path))
            {
                Add(result, true, code, path, "Required workspace directory is missing.");
            }
        }

        ValidateAcceptance(workspace.Manifest, result);

        if (File.Exists(workspace.RequirementsFile))
        {
            var requirements = new RequirementCaptureLoader().Load(workspace.RequirementsFile);
            var requirementsResult = new RequirementCaptureValidator().Validate(requirements);
            foreach (var error in requirementsResult.Errors)
            {
                Add(result, true, error.Code, error.Path, error.Message);
            }
            foreach (var warning in requirementsResult.Warnings)
            {
                Add(result, false, warning.Code, warning.Path, warning.Message);
            }
        }
        else
        {
            Add(result, true, "onboarding.requirements.missing", "$.paths.requirementsPath", "RequirementCapture file is missing.");
        }

        if (!File.Exists(Path.Combine(workspace.TemplateDirectory, "template.json")))
        {
            Add(result, true, "onboarding.template.missing", "$.paths.templateDir", "TemplatePackage template.json is missing.");
        }

        if (!File.Exists(workspace.DocumentPath))
        {
            Add(result, true, "onboarding.fixture.documentMissing", "$.paths.fixturesDir", "Fixture document.json is missing.");
        }

        result.Errors = result.Errors.OrderBy(e => e.Code, StringComparer.Ordinal).ThenBy(e => e.Path, StringComparer.Ordinal).ToList();
        result.Warnings = result.Warnings.OrderBy(e => e.Code, StringComparer.Ordinal).ThenBy(e => e.Path, StringComparer.Ordinal).ToList();
        return result;
    }

    public static bool IsInvalidRelativePath(string? value)
    {
        if (string.IsNullOrWhiteSpace(value) || Path.IsPathRooted(value))
        {
            return true;
        }

        return value.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries).Any(segment => segment == "..");
    }

    internal static IEnumerable<(string Name, string Value)> EnumeratePaths(OnboardingWorkspacePaths paths)
    {
        yield return ("sourceDocumentsDir", paths.SourceDocumentsDir);
        yield return ("requirementsPath", paths.RequirementsPath);
        yield return ("templateDir", paths.TemplateDir);
        yield return ("fixturesDir", paths.FixturesDir);
        yield return ("baselinesDir", paths.BaselinesDir);
        yield return ("reportsDir", paths.ReportsDir);
        yield return ("artifactsDir", paths.ArtifactsDir);
    }

    private static void ValidateAcceptance(OnboardingWorkspaceManifest manifest, OnboardingWorkspaceValidationResult result)
    {
        if (manifest.Acceptance.ReviewStatus == "humanAccepted"
            && (string.IsNullOrWhiteSpace(manifest.Acceptance.AcceptedBy) || string.IsNullOrWhiteSpace(manifest.Acceptance.AcceptedAt)))
        {
            Add(result, true, "onboarding.acceptance.humanReviewMissing", "$.acceptance", "Human accepted workspaces must record acceptedBy and acceptedAt.");
        }

        if (!string.Equals(manifest.Institution.RedactionPolicy, "publicSourceExample", StringComparison.Ordinal))
        {
            return;
        }

        if (manifest.Acceptance.ReviewStatus == "notReviewed")
        {
            Add(result, true, "onboarding.acceptance.publicSourceNotReviewed", "$.acceptance.reviewStatus", "Public-source examples must record at least machineChecked acceptance.");
        }

        var requiredScopes = new[]
        {
            "privacy",
            "schema",
            "inputValidation",
            "render",
            "formatConformance",
            "templateRegression",
            "baselineCompare",
            "package"
        };
        foreach (var scope in requiredScopes)
        {
            if (!manifest.Acceptance.AcceptedScope.Contains(scope, StringComparer.Ordinal))
            {
                Add(result, true, "onboarding.acceptance.scopeMissing", "$.acceptance.acceptedScope", $"Public-source acceptance is missing scope '{scope}'.");
            }
        }
    }

    private static void Add(OnboardingWorkspaceValidationResult result, bool error, string code, string path, string message)
    {
        var issue = new OnboardingWorkspaceIssue { Code = code, Path = path, Message = message };
        if (error)
        {
            result.Errors.Add(issue);
        }
        else
        {
            result.Warnings.Add(issue);
        }
    }

    private static string LocateSchema(string name)
    {
        var current = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (current is not null)
        {
            var candidate = Path.Combine(current.FullName, "schemas", name);
            if (File.Exists(candidate))
            {
                return candidate;
            }
            current = current.Parent;
        }
        return string.Empty;
    }
}

public sealed class OnboardingWorkspaceValidationResult
{
    public bool IsValid => Errors.Count == 0;
    public List<OnboardingWorkspaceIssue> Errors { get; set; } = [];
    public List<OnboardingWorkspaceIssue> Warnings { get; set; } = [];
}

public sealed class OnboardingWorkspaceIssue
{
    public string Code { get; set; } = string.Empty;
    public string Path { get; set; } = "$";
    public string Message { get; set; } = string.Empty;

    public override string ToString() => $"{Code} at {Path}: {Message}";
}
